# application.yml写法
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: demo888
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  hibernate:
    ddl-auto: update